import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/(frontend)/components/Header";
import StyledComponentsRegistry from "../libs/styled-components/registry";
import { Toaster } from "react-hot-toast";
import { Footer } from "./_shared/components/Footer";
import MainContainer from "./components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#121212" }} className={inter.className}>
        <StyledComponentsRegistry>
          <Header />
          <MainContainer>{children}</MainContainer>
          <Footer />
          <Toaster />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
